from flask_wtf import FlaskForm
from wtforms import SubmitField, IntegerField, SelectField, DecimalField
from wtforms.validators import DataRequired, ValidationError

UNIT_TYPES = [
  ('bar spoon', 'bar spoon'),
  ('blender', 'blender'),
  ('bottle', 'bottle'),
  ('bottles', 'bottles'),
  ('can', 'can'),
  ('cans', 'cans'),
  ('cl', 'cl'),
  ('cube', 'cube'),
  ('cubes', 'cubes'),
  ('cup', 'cup'),
  ('cups', 'cups'),
  ('dash', 'dash'),
  ('dashes', 'dashes'),
  ('dl', 'dl'),
  ('drop', 'drop'),
  ('drops', 'drops'),
  ('fifth', 'fifth'),
  ('finger', 'finger'),
  ('fingers', 'fingers'),
  ('gal', 'gal'),
  ('garnish', 'garnish'),
  ('glass', 'glass'),
  ('gr', 'gr'),
  ('handful', 'handful'),
  ('inch', 'inch'),
  ('jigger', 'jigger'),
  ('jiggers', 'jiggers'),
  ('juice', 'juice'),
  ('kg', 'kg'),
  ('l', 'l'),
  ('lb', 'lb'),
  ('leaf', 'leaf'),
  ('ml', 'ml'),
  ('oz', 'oz'),
  ('package', 'package'),
  ('packages', 'packages'),
  ('part', 'part'),
  ('parts', 'parts'),
  ('peel', 'peel'),
  ('piece', 'piece'),
  ('pieces', 'pieces'),
  ('pinch', 'pinch'),
  ('pinches', 'pinches'),
  ('pint', 'pint'),
  ('qt', 'qt'),
  ('scoop', 'scoop'),
  ('scoops', 'scoops'),
  ('shot', 'shot'),
  ('shots', 'shots'),
  ('slice', 'slice'),
  ('splash', 'splash'),
  ('splashes', 'splashes'),
  ('sprig', 'sprig'),
  ('sprigs', 'sprigs'),
  ('stick', 'stick'),
  ('sticks', 'sticks'),
  ('tbsp', 'tbsp'),
  ('top off', 'top off'),
  ('to taste', 'to taste'),
  ('tsp', 'tsp'),
  ('twist', 'twist'),
  ('unit', 'unit'),
  ('units', 'units'),
  ('wedge', 'wedge'),
  ('wedges', 'wedges'),
  ('whole', 'whole')
]

class RecipeIngredientForm(FlaskForm):
    amount = DecimalField('Name', places=2, validators=[DataRequired()])
    unit = SelectField('Description', choices=UNIT_TYPES, validators=[DataRequired()])
    ingredient_id = IntegerField('Ingredient Id', validators=[DataRequired()])
    recipe_id = IntegerField('Recipe Id', validators=[DataRequired()])
    submit = SubmitField('Submit')
