export const GET_RECIPES = 'GET_RECIPES';
export const GET_A_RECIPE = 'GET_A_RECIPE';
export const GET_USER_RECIPES = 'GET_USER_RECIPES';
export const POST_RECIPE = 'POST_RECIPE';
export const POST_RECIPE_IMAGE = 'POST_RECIPE_IMAGE';
export const EDIT_RECIPE = 'EDIT_RECIPE';
export const DELETE_RECIPE = 'DELETE_RECIPE';
export const RANDOM_RECIPE = 'RANDOM_RECIPE';

export const GET_INGREDIENTS = 'GET_INGREDIENTS';
export const GET_AN_INGREDIENT = 'GET_AN_INGREDIENT';
export const POST_INGREDIENT = 'POST_INGREDIENT';
export const POST_INGREDIENT_IMAGE = 'POST_INGREDIENT_IMAGE';

export const GET_RECIPE_INGREDIENTS = 'GET_RECIPE_INGREDIENTS';
export const POST_RECIPE_INGREDIENTS = 'POST_RECIPE_INGREDIENTS';
export const EDIT_RECIPE_INGREDIENTS = 'EDIT_RECIPE_INGREDIENTS';

export const GET_BAR = 'GET_BAR';
export const POST_BAR = 'POST_BAR';
export const EDIT_BAR = 'EDIT_BAR';

export const GET_REVIEWS = 'GET_REVIEWS';
export const POST_REVIEW = 'POST_REVIEW';
export const EDIT_REVIEW = 'EDIT_REVIEW';
export const DELETE_REVIEW = 'DELETE_REVIEW';

export const GET_TOASTS = 'GET_TOASTS';
export const POST_TOASTS = 'POST_TOASTS';
export const DELETE_TOASTS = 'DELETE_TOASTS';
